# Generated by Django 2.1.3 on 2018-11-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plural', '0003_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player To Move'), ('S', 'Second Player To Move'), ('W', 'First Player Wins'), ('L', 'Second Player Wins'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
