# Generated by Django 2.1.3 on 2018-11-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plural', '0004_auto_20181125_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
